---

downloads: ~/.ansible-downloads/

# Dotfiles
configure_dotfiles: true
dotfiles_repo: git@github.com:glennbrown/dotfiles.git
dotfiles_repo_version: main
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/Documents/dotfiles
dotfiles_files:
  - .zshrc
  - .inputrc
  - .macos_defaults
  - .vimrc
  - .bashrc
  - .bash_profile

configure_terminal: false

configure_macos: true
macos_services:
  - Dock
  - Finder
  - SystemUIServer
macos_default_script: "~/.macos_defaults --no-restart"
macos_default_settings: []

## Set to 'true' to configure the Dock via dockutil.
configure_dock: false
dockitems_remove: []
# - Launchpad
# - TV
# - Podcasts
# - 'App Store'
dockitems_persist: []
# - name: "Sublime Text"
#   path: "/Applications/Sublime Text.app/"
#   pos: 5

homebrew_taps:
  - homebrew/cask-fonts
  - homebrew/command-not-found
  - homebrew/services

homebrew_installed_packages:
  - bash
  - bash-completion@2
  - btop
  - brew-cask-completion
  - coreutils
  - ctop
  - curl
  - dialog
  - diceware
  - fastfetch
  - ffmpeg
  - fio
  - flac
  - fwupd
  - gawk
  - gnupg
  - gnu-sed
  - gnu-tar
  - go
  - htop
  - iftop
  - iperf3
  - jq
  - just
  - lame
  - lesspipe
  - lz4
  - lzo
  - mactop
  - mc
  - nano
  - nanorc
  - ncdu
  - ncurses
  - neofetch
  - nmap
  - p7zip
  - perl
  - pv
  - qemu
  - ruby
  - screen
  - screenresolution
  - smartmontools
  - snappy
  - socat
  - svt-av1
  - tmux
  - tree
  - webp
  - wget
  - when
  - x264
  - x265
  - xvid
  - xz
  - yt-dlp
  - zsh-autosuggestions
  - zsh-history-substring-search

homebrew_cask_apps:
  - 1password
  - 1password-cli
  - balenaetcher
  - docker
  - google-chrome
  - handbrake
  - iterm2
  - plex-media-server
  - prowlarr
  - qbittorrent
  - radarr
  - sabnzbd
  - sonarr
  - timemachineeditor
  - utm
  - visual-studio-code

mas_installed_apps: []