---
roles:
  - name: elliotweiser.osx-command-line-tools
  - name: geerlingguy.dotfiles

  # IronicBadgers Roles
  - src: https://github.com/glennbrown/ansible-role-docker-compose-generator.git
    name: ironicbadger.docker_compose_generator
    scm: git
  

collections:
  - name: geerlingguy.mac