---

homebrew_user: gbrown
homebrew_group: admin

configure_dock: true

dockitems_remove:
  - Mail
  - Maps
  - Photos
  - FaceTime
  - Calendar
  - Contacts
  - Reminders 
  - Freeform
  - TV
  - Music
  - News
  - 'App Store'
  - 'System Settings'

dockitems_persist:
  - name: Launchpad
    path: "/System/Applications/Launchpad.app/"
    pos: 1
  - name: Safari
    path: "/Applications/Safari.app/"
    pos: 2
  - name: "Google Chrome"
    path: "/Applications/Google Chrome.app/"
    pos: 3
  - name: Messages
    path: "/System/Applications/Messages.app/"
    pos: 4
  - name: iTerm
    path: "/Applications/iTerm.app/"
    pos: 5
  - name: 1Password
    path: "/Applications/1Password.app/"
    pos: 6
  - name: Passwords
    path: "/System/Applications/Passwords.app/"
    pos: 7
  - name: BBEdit
    path: "/Applications/BBEdit.app/"
    pos: 8
  - name: "Visual Studio Code"
    path: "/Applications/Visual Studio Code.app/"
    pos: 9
  - name: "Plex Media Server"
    path: "/Applications/Plex Media Server.app/"
    pos: 10
  - name: "qBittorrent"
    path: "/Applications/qBittorrent.app/"
    pos: 11
  - name: UTM
    path: "/Applications/UTM.app/"
    pos: 12
    
mas_installed_apps:
  # Tools
  - { id: 1611378436, name: "Pure Paste" }
  
  # Safari Extensions
  - { id: 1569813296, name: "1Password for Safari" }
  - { id: 1662217862, name: "Wipr" }

  # Dev Tools
  - { id: 497799835, name: "Xcode" }
  - { id: 404009241, name: "BBEdit" }

macos_default_settings:
  # General UI/UX
  # Expand save panel by default
  - domain: NSGlobalDomain
    key: NSNavPanelExpandedStateForSaveMode
    type: bool
    value: true
  # Expand print panel by default
  - domain: NSGlobalDomain
    key: PMPrintingExpandedStateForPrint
    type: bool
    value: true
  # Disable smart quotes as they’re annoying when typing code
  - domain: NSGlobalDomain
    key: NSAutomaticQuoteSubstitutionEnabled
    type: bool
    value: true
  # Disable smart dashes as they’re annoying when typing code
  - domain: NSGlobalDomain
    key: NSAutomaticDashSubstitutionEnabled
    type: bool
    value: true
  # Automatically quit printer app once the print jobs complete
  - domain: com.apple.print.PrintingPrefs
    key: "Quit When Finished"
    type: bool
    value: true
  
  # Trackpad, mouse, keyboard, Bluetooth accessories, and input
  # Trackpad: Haptic feedback (light, silent clicking)
  - domain: com.apple.AppleMultitouchTrackpad
    key: FirstClickThreshold
    type: int
    value: 0
  - domain: com.apple.AppleMultitouchTrackpad
    key: ActuationStrength
    type: int
    value: 0
  # Trackpad: map bottom right corner to right-click (requires restart!)
  - domain: com.apple.driver.AppleBluetoothMultitouch.trackpad
    key: TrackpadRightClick
    type: bool
    value: true
  - domain: com.apple.driver.AppleBluetoothMultitouch.trackpad
    key: TrackpadCornerSecondaryClick
    type: int
    value: 2
  - domain: NSGlobalDomain
    key: ContextMenuGesture
    type: int
    value: 1
  # Disable press-and-hold for keys in favor of key repeat
  - domain: NSGlobalDomain
    key: ApplePressAndHoldEnabled
    type: bool
    value: false
  # Set a blazingly fast keyboard repeat rate, and make it happen more quickly.
  # (The KeyRepeat option requires logging out and back in to take effect.)
  - domain: NSGlobalDomain
    key: InitialKeyRepeat
    type: int
    value: '20'
  - domain: NSGlobalDomain
    key: KeyRepeat
    type: int
    value: '1'
  # Disable auto-correct
  - domain: NSGlobalDomain
    key: NSAutomaticSpellingCorrectionEnabled
    type: bool
    value: false
  
  # Screenshots
  # Save screenshots to iCloud Drive Screenshots folder
  - domain: com.apple.screencapture
    key: location
    type: string
    value: "~/Documents/Screenshots"
  # Save as jpg
  - domain: com.apple.screencapture
    key: type
    type: string
    value: "jpg"
  # Disable shadow on screenshots
  - domain: com.apple.screencapture
    key: disable-shadow
    type: bool
    value: true

  # Finder
  # Show icons for hard drives, servers, and removable media on the desktop
  - domain: com.apple.finder
    key: ShowExternalHardDrivesOnDesktop
    type: bool
    value: true
  - domain: com.apple.finder
    key: ShowHardDrivesOnDesktop
    type: bool
    value: true
  - domain: com.apple.finder
    key: ShowMountedServersOnDesktop
    type: bool
    value: true
  - domain: com.apple.finder
    key: ShowRemovableMediaOnDesktop
    type: bool
    value: true
  # Finder: Show status bar
  - domain: com.apple.finder
    key: ShowStatusBar
    type: bool
    value: true
  # Finder: Show Path Bar
  - domain: com.apple.finder
    key: ShowPathbar
    type: bool
    value: true
  # Finder: Keep Folders on top
  - domain: com.apple.finder
    key: _FXSortFoldersFirst
    type: bool
    value: true
  # Automatically Empty Recycle bin after 30 days
  - domain: com.apple.finder
    key: FXRemoveOldTrashItems
    type: bool
    value: true
  # Finder: allow text selection in Quick Look
  - domain: com.apple.finder
    key: QLEnableTextSelection
    type: bool
    value: true
  # When performing a search, search the current folder by default
  - domain: com.apple.finder
    key: FXDefaultSearchScope
    type: string
    value: "SCcf"
  # Disable the warning when changing a file extension
  - domain: com.apple.finder
    key: FXEnableExtensionChangeWarning
    type: bool
    value: true
  # Enable spring loading for directories
  - domain: NSGlobalDomain
    key: com.apple.springing.enabled
    type: bool
    value: true
  # Remove the spring loading delay for directories
  - domain: NSGlobalDomain
    key: com.apple.springing.delay
    type: float
    value: '0.1'
  # Avoid creating .DS_Store files on network volumes
  - domain: com.apple.desktopservices
    key: DSDontWriteNetworkStores
    type: bool
    value: true
  # Use list view in all Finder windows by default
  # Four-letter codes for the other view modes: `icnv`, `Nlsv`, `clmv`, `Flwv`
  - domain: com.apple.finder
    key: FXPreferredViewStyle
    type: string
    value: "Nlsv"
  
  # Dock, Dashboard and hot corners
  # Set the icon size of Dock items
  - domain: com.apple.dock
    key: tilesize
    type: int
    value: '32'
  # Make Dock icons of hidden applications translucent
  - domain: com.apple.dock
    key: showhidden
    type: bool
    value: true
  # Autohide Dock
  - domain: com.apple.dock
    key: autohide
    type: bool
    value: true
  # Speed up hide/show dock animations
  - domain: com.apple.dock
    key: autohide-delay
    type: float
    value: '0'
  - domain: com.apple.dock
    key: autohide-time-modifier
    type: float
    value: '0.15'
  # Use scale effect with dock
  - domain: com.apple.dock
    key: mineffect
    type: string
    value: "scale"
  # Botton Align Dock
  - domain: com.apple.dock
    key: orientation
    type: string
    value: "bottom"
  # Don't show recent apps
  - domain: com.apple.dock
    key: show-recents
    type: bool
    value: false
  # Expose/Mission Control Group Apps
  - domain: com.apple.dock
    key: expose-group-apps
    type: bool
    value: true
  # Hot corners
  # Possible values:
  #  0: no-op
  #  2: Mission Control
  #  3: Show application windows
  #  4: Desktop
  #  5: Start screen saver
  #  6: Disable screen saver
  #  7: Dashboard
  # 10: Put display to sleep
  # 11: Launchpad
  # 12: Notification Center
  # Bottom right screen corner → Mission Control
  #- domain: com.apple.dock
  #  key: wvous-br-corner
  #  type: int
  #  value: '2'
  #- domain: com.apple.dock
  #  key: wvous-br-modifier
  #  type: int
  #  value: '0'
  # Top Right Corner → Put Display to Sleep with Command Key Modifier
  #- domain: com.apple.dock
  #  key: wvous-tr-corner
  #  type: int
  #  value: '10'
  #- domain: com.apple.dock
  #  key: wvous-tr-modifier
  #  type: int
  #  value: '1048576'
  # Bottom left screen corner → Desktop
  #- domain: com.apple.dock
  #  key: wvous-bl-corner
  #  type: int
  #  value: '4'
  #- domain: com.apple.dock
  #  key: wvous-bl-modifier
  #  type: int
  #  value: '0'
  
  # Safari & Webkit
  # Enable the Develop menu and the Web Inspector in Safari
  - domain: com.apple.safari
    key: IncludeDevelopMenu
    type: bool
    value: true
  - domain: com.apple.safari
    key: WebKitDeveloperExtrasEnabledPreferenceKey
    type: bool
    value: true
  - domain: com.apple.safari
    key: "com.apple.Safari.ContentPageGroupIdentifier.WebKit2DeveloperExtrasEnabled"
    type: bool
    value: true
  # Add a context menu item for showing the Web Inspector in web views
  - domain: NSGlobalDomain
    key: WebKitDeveloperExtras
    type: bool
    value: true
  # Show Full URL in Address Bar
  - domain: com.apple.safari
    key: ShowFullURLInSmartSearchField
    type: bool
    value: true

  # Mail
  # Copy email addresses as `foo@example.com` instead of `Foo Bar <foo@example.com>` in Mail.app
  - domain: com.apple.mail
    key: AddressesIncludeNameOnPasteboard
    type: bool
    value: true

  # Activity Monitor
  # Show the main window when launching Activity Monitor
  - domain: com.apple.ActivityMonitor
    key: OpenMainWindow
    type: bool
    value: true
  # Show all processes in Activity Monitor
  - domain: com.apple.ActivityMonitor
    key: ShowCategory
    type: int
    value: '0'
  
  # App Store
  # Disable in-app rating requests from apps downloaded from the App Store.
  - domain: com.apple.appstore
    key: InAppReviewEnabled
    type: int
    value: '0'

  # Time Machine
  # Don't offer new disks for Time Machine backup
  - domain: com.apple.TimeMachine
    key: DoNotOfferNewDisksForBackup
    type: bool
    value: true
